### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pana1990** [pana1990/yii2-app#1]
TODO
----

 - [ ] Add docs
 - [x] Add dotenv
 - [ ] Add [deployer](http://deployer.org/)
 - [ ] [Shortcuts useful ](https://github.com/samdark/yii2-cookbook/blob/master/book/structure-global-functions.md)
 - [ ] [IDE autocompletion for custom components](https://github.com/samdark/yii2-cookbook/blob/master/book/ide-autocompletion.md)
 - [ ] More features...

**Comment by Arrow90** [comment]
You could include errors pages for unexpected requests, if you consider it of relevance.
